### PR TITLE
Add platform support

### PR DESCRIPTION
**Pull request by ldesrosi**
Contains three major changes:
1. Update to README OS support statement
2. Fix to the generateConnectionProfile which was failing when the gateways folder did not exist
3. Added the PLATFORM and UNIX_SOCK to the docker-compose to ensure the network works with Mac M1 and address a recent docker issue with unix socket.

### CODE REVIEW

**Comment by VRamakrishna** [comment]
@ldesrosi When I ran `./trade.sh up`, it failed with the following error:
```
Starting network
"--platform" is only supported on a Docker daemon with experimental features enabled
```

I was able to get past this by creating a file `/etc/docker/daemon.json` and adding the following contents to it:
```
{
    "experimental": true
}
```
Then I restarted the Docker daemon using `sudo systemctl restart docker`.

How do you suggest we handle this? Like me, others who are running Docker in default mode will not have experimental features enabled. Should we add a hint about this in `trade.sh` upon an error? Or should we try to automatically catch the error and run without the `--platform` switch?

**Comment by VRamakrishna** [comment]
@ldesrosi I removed the npm package dependency which was raising the vulnerability alert. Please see my latest commit.

**Comment by ldesrosi** [comment]
@VRamakrishna, what version are you using? I am on V3.0.4 and I am running with `experimental=false`.

If you're on 2.x, could I ask you to try upgrading to 3.x and see if you have the issue?

If it is part of the official distribution of v3.x, I would suggest that we make it the minimum supported and add the fix to the Errata page.  What do you think?

**Comment by VRamakrishna** [comment]
@ldesrosi I'm not running Docker Desktop on my Ubuntu VM, just the Docker Engine (version 19.03.8), so I can't match the versions numbers you mentioned. But I just tried running on a different machine with Docker Engine version 20.10.3 and it worked without requiring any changes to the config settings.

So I think it should be OK to merge, and I'll approve it.

Can you add an entry to the Errata page? Also, can we call it the Troubleshooting page? We can use a separate Errata page for any book corrections we need to point out.

**Review by VRamakrishna — APPROVED** [review]

**Pull request merged**
